# Generated by Django 4.1.4 on 2022-12-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.FileField(upload_to="pictures/"),
        ),
    ]
