# Generated by Django 4.1.4 on 2022-12-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_image_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
    ]
