# Generated by Django 4.1.4 on 2022-12-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_picture_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="url",
            new_name="picture",
        ),
    ]
